#默认使用配置
spring:
  #时间相差八个小时问题
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #开发模式
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true
    multipart:
    max-file-size: 10MB
    max-request-size: 10MB
  resources:
    static-locations: classpath:/templates/
#公共配置与profiles选择无关
mybatis:
  mapperLocations: classpath*:mapper/*.xml
